/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated.index'
import { Route as AuthenticatedProyectosRouteImport } from './routes/_authenticated.proyectos'
import { Route as AuthenticatedNoConformidadesRouteImport } from './routes/_authenticated.no-conformidades'
import { Route as AuthenticatedDocumentosRouteImport } from './routes/_authenticated.documentos'
import { Route as AuthenticatedConfiguracionRouteImport } from './routes/_authenticated.configuracion'
import { Route as AuthenticatedCalendarioRouteImport } from './routes/_authenticated.calendario'
import { Route as AuthenticatedAuditoriasRouteImport } from './routes/_authenticated.auditorias'
import { Route as AuthenticatedDocumentosIndexRouteImport } from './routes/_authenticated.documentos.index'
import { Route as AuthenticatedAuditoriasIndexRouteImport } from './routes/_authenticated.auditorias.index'
import { Route as ApiPublicEnsureBucketsRouteImport } from './routes/api/public/ensure-buckets'
import { Route as AuthenticatedDocumentosRedRouteImport } from './routes/_authenticated.documentos.red'
import { Route as AuthenticatedAuditoriasIdRouteImport } from './routes/_authenticated.auditorias.$id'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedProyectosRoute = AuthenticatedProyectosRouteImport.update({
  id: '/proyectos',
  path: '/proyectos',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedNoConformidadesRoute =
  AuthenticatedNoConformidadesRouteImport.update({
    id: '/no-conformidades',
    path: '/no-conformidades',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedDocumentosRoute = AuthenticatedDocumentosRouteImport.update({
  id: '/documentos',
  path: '/documentos',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedConfiguracionRoute =
  AuthenticatedConfiguracionRouteImport.update({
    id: '/configuracion',
    path: '/configuracion',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedCalendarioRoute = AuthenticatedCalendarioRouteImport.update({
  id: '/calendario',
  path: '/calendario',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAuditoriasRoute = AuthenticatedAuditoriasRouteImport.update({
  id: '/auditorias',
  path: '/auditorias',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDocumentosIndexRoute =
  AuthenticatedDocumentosIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedDocumentosRoute,
  } as any)
const AuthenticatedAuditoriasIndexRoute =
  AuthenticatedAuditoriasIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedAuditoriasRoute,
  } as any)
const ApiPublicEnsureBucketsRoute = ApiPublicEnsureBucketsRouteImport.update({
  id: '/api/public/ensure-buckets',
  path: '/api/public/ensure-buckets',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedDocumentosRedRoute =
  AuthenticatedDocumentosRedRouteImport.update({
    id: '/red',
    path: '/red',
    getParentRoute: () => AuthenticatedDocumentosRoute,
  } as any)
const AuthenticatedAuditoriasIdRoute =
  AuthenticatedAuditoriasIdRouteImport.update({
    id: '/$id',
    path: '/$id',
    getParentRoute: () => AuthenticatedAuditoriasRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/auth': typeof AuthRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/auditorias': typeof AuthenticatedAuditoriasRouteWithChildren
  '/calendario': typeof AuthenticatedCalendarioRoute
  '/configuracion': typeof AuthenticatedConfiguracionRoute
  '/documentos': typeof AuthenticatedDocumentosRouteWithChildren
  '/no-conformidades': typeof AuthenticatedNoConformidadesRoute
  '/proyectos': typeof AuthenticatedProyectosRoute
  '/auditorias/$id': typeof AuthenticatedAuditoriasIdRoute
  '/documentos/red': typeof AuthenticatedDocumentosRedRoute
  '/api/public/ensure-buckets': typeof ApiPublicEnsureBucketsRoute
  '/auditorias/': typeof AuthenticatedAuditoriasIndexRoute
  '/documentos/': typeof AuthenticatedDocumentosIndexRoute
}
export interface FileRoutesByTo {
  '/auth': typeof AuthRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/calendario': typeof AuthenticatedCalendarioRoute
  '/configuracion': typeof AuthenticatedConfiguracionRoute
  '/no-conformidades': typeof AuthenticatedNoConformidadesRoute
  '/proyectos': typeof AuthenticatedProyectosRoute
  '/': typeof AuthenticatedIndexRoute
  '/auditorias/$id': typeof AuthenticatedAuditoriasIdRoute
  '/documentos/red': typeof AuthenticatedDocumentosRedRoute
  '/api/public/ensure-buckets': typeof ApiPublicEnsureBucketsRoute
  '/auditorias': typeof AuthenticatedAuditoriasIndexRoute
  '/documentos': typeof AuthenticatedDocumentosIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/auth': typeof AuthRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/_authenticated/auditorias': typeof AuthenticatedAuditoriasRouteWithChildren
  '/_authenticated/calendario': typeof AuthenticatedCalendarioRoute
  '/_authenticated/configuracion': typeof AuthenticatedConfiguracionRoute
  '/_authenticated/documentos': typeof AuthenticatedDocumentosRouteWithChildren
  '/_authenticated/no-conformidades': typeof AuthenticatedNoConformidadesRoute
  '/_authenticated/proyectos': typeof AuthenticatedProyectosRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_authenticated/auditorias/$id': typeof AuthenticatedAuditoriasIdRoute
  '/_authenticated/documentos/red': typeof AuthenticatedDocumentosRedRoute
  '/api/public/ensure-buckets': typeof ApiPublicEnsureBucketsRoute
  '/_authenticated/auditorias/': typeof AuthenticatedAuditoriasIndexRoute
  '/_authenticated/documentos/': typeof AuthenticatedDocumentosIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/sitemap.xml'
    | '/auditorias'
    | '/calendario'
    | '/configuracion'
    | '/documentos'
    | '/no-conformidades'
    | '/proyectos'
    | '/auditorias/$id'
    | '/documentos/red'
    | '/api/public/ensure-buckets'
    | '/auditorias/'
    | '/documentos/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/auth'
    | '/sitemap.xml'
    | '/calendario'
    | '/configuracion'
    | '/no-conformidades'
    | '/proyectos'
    | '/'
    | '/auditorias/$id'
    | '/documentos/red'
    | '/api/public/ensure-buckets'
    | '/auditorias'
    | '/documentos'
  id:
    | '__root__'
    | '/_authenticated'
    | '/auth'
    | '/sitemap.xml'
    | '/_authenticated/auditorias'
    | '/_authenticated/calendario'
    | '/_authenticated/configuracion'
    | '/_authenticated/documentos'
    | '/_authenticated/no-conformidades'
    | '/_authenticated/proyectos'
    | '/_authenticated/'
    | '/_authenticated/auditorias/$id'
    | '/_authenticated/documentos/red'
    | '/api/public/ensure-buckets'
    | '/_authenticated/auditorias/'
    | '/_authenticated/documentos/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  AuthRoute: typeof AuthRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  ApiPublicEnsureBucketsRoute: typeof ApiPublicEnsureBucketsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/proyectos': {
      id: '/_authenticated/proyectos'
      path: '/proyectos'
      fullPath: '/proyectos'
      preLoaderRoute: typeof AuthenticatedProyectosRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/no-conformidades': {
      id: '/_authenticated/no-conformidades'
      path: '/no-conformidades'
      fullPath: '/no-conformidades'
      preLoaderRoute: typeof AuthenticatedNoConformidadesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/documentos': {
      id: '/_authenticated/documentos'
      path: '/documentos'
      fullPath: '/documentos'
      preLoaderRoute: typeof AuthenticatedDocumentosRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/configuracion': {
      id: '/_authenticated/configuracion'
      path: '/configuracion'
      fullPath: '/configuracion'
      preLoaderRoute: typeof AuthenticatedConfiguracionRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/calendario': {
      id: '/_authenticated/calendario'
      path: '/calendario'
      fullPath: '/calendario'
      preLoaderRoute: typeof AuthenticatedCalendarioRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/auditorias': {
      id: '/_authenticated/auditorias'
      path: '/auditorias'
      fullPath: '/auditorias'
      preLoaderRoute: typeof AuthenticatedAuditoriasRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/documentos/': {
      id: '/_authenticated/documentos/'
      path: '/'
      fullPath: '/documentos/'
      preLoaderRoute: typeof AuthenticatedDocumentosIndexRouteImport
      parentRoute: typeof AuthenticatedDocumentosRoute
    }
    '/_authenticated/auditorias/': {
      id: '/_authenticated/auditorias/'
      path: '/'
      fullPath: '/auditorias/'
      preLoaderRoute: typeof AuthenticatedAuditoriasIndexRouteImport
      parentRoute: typeof AuthenticatedAuditoriasRoute
    }
    '/api/public/ensure-buckets': {
      id: '/api/public/ensure-buckets'
      path: '/api/public/ensure-buckets'
      fullPath: '/api/public/ensure-buckets'
      preLoaderRoute: typeof ApiPublicEnsureBucketsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/documentos/red': {
      id: '/_authenticated/documentos/red'
      path: '/red'
      fullPath: '/documentos/red'
      preLoaderRoute: typeof AuthenticatedDocumentosRedRouteImport
      parentRoute: typeof AuthenticatedDocumentosRoute
    }
    '/_authenticated/auditorias/$id': {
      id: '/_authenticated/auditorias/$id'
      path: '/$id'
      fullPath: '/auditorias/$id'
      preLoaderRoute: typeof AuthenticatedAuditoriasIdRouteImport
      parentRoute: typeof AuthenticatedAuditoriasRoute
    }
  }
}

interface AuthenticatedAuditoriasRouteChildren {
  AuthenticatedAuditoriasIdRoute: typeof AuthenticatedAuditoriasIdRoute
  AuthenticatedAuditoriasIndexRoute: typeof AuthenticatedAuditoriasIndexRoute
}

const AuthenticatedAuditoriasRouteChildren: AuthenticatedAuditoriasRouteChildren =
  {
    AuthenticatedAuditoriasIdRoute: AuthenticatedAuditoriasIdRoute,
    AuthenticatedAuditoriasIndexRoute: AuthenticatedAuditoriasIndexRoute,
  }

const AuthenticatedAuditoriasRouteWithChildren =
  AuthenticatedAuditoriasRoute._addFileChildren(
    AuthenticatedAuditoriasRouteChildren,
  )

interface AuthenticatedDocumentosRouteChildren {
  AuthenticatedDocumentosRedRoute: typeof AuthenticatedDocumentosRedRoute
  AuthenticatedDocumentosIndexRoute: typeof AuthenticatedDocumentosIndexRoute
}

const AuthenticatedDocumentosRouteChildren: AuthenticatedDocumentosRouteChildren =
  {
    AuthenticatedDocumentosRedRoute: AuthenticatedDocumentosRedRoute,
    AuthenticatedDocumentosIndexRoute: AuthenticatedDocumentosIndexRoute,
  }

const AuthenticatedDocumentosRouteWithChildren =
  AuthenticatedDocumentosRoute._addFileChildren(
    AuthenticatedDocumentosRouteChildren,
  )

interface AuthenticatedRouteChildren {
  AuthenticatedAuditoriasRoute: typeof AuthenticatedAuditoriasRouteWithChildren
  AuthenticatedCalendarioRoute: typeof AuthenticatedCalendarioRoute
  AuthenticatedConfiguracionRoute: typeof AuthenticatedConfiguracionRoute
  AuthenticatedDocumentosRoute: typeof AuthenticatedDocumentosRouteWithChildren
  AuthenticatedNoConformidadesRoute: typeof AuthenticatedNoConformidadesRoute
  AuthenticatedProyectosRoute: typeof AuthenticatedProyectosRoute
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAuditoriasRoute: AuthenticatedAuditoriasRouteWithChildren,
  AuthenticatedCalendarioRoute: AuthenticatedCalendarioRoute,
  AuthenticatedConfiguracionRoute: AuthenticatedConfiguracionRoute,
  AuthenticatedDocumentosRoute: AuthenticatedDocumentosRouteWithChildren,
  AuthenticatedNoConformidadesRoute: AuthenticatedNoConformidadesRoute,
  AuthenticatedProyectosRoute: AuthenticatedProyectosRoute,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  AuthRoute: AuthRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  ApiPublicEnsureBucketsRoute: ApiPublicEnsureBucketsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
